# Redirect with a 301
[[redirects]]
from = "/"
to = "/home/popularity/desc/1"
status = 301

# Redirect with a 302
[[redirects]]
from = "/"
to = "/home/popularity/desc/1"
status = 302

# Show a custom 404 for this path
[[redirects]]
from = "/"
to = "/home/popularity/desc/1"
status = 404

# Rewrite a path
[[redirects]]
from = "/"
to = "//home/popularity/desc/1"
status = 200