# Redirect with a 301
[[redirects]]
from = "/"
to = "/home/popularity/desc/1"
status = 301

# Redirect with a 302
[[redirects]]
from = "/"
to = "/home/popularity/desc/1"
status = 302

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
